# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:/v6Q1eSC6vhEQM9X2Esp5ClhNLS+hYR2byMB09+uRss=,iv:V2j1OMwCp/ctXh9VbBgFmTLLCi1YTjAmiT2Ws9jGQYQ=,tag:Cfji5uwf/xCnfvN/OYuG1A==,type:str]
sops:
  age:
    - recipient: age14eunmzg58swzewu9nqkv06zpj8e9pqhv37efuwx32ueum30wtcnqrmsayc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYzNBTHpjRERWVWE1YWRk
        UDFYbW1Pc1ViTkM1Mk1XQi8wVmdUMWpCRFRFCnRqczd6SWtCTGlXNDZ4SjJVWUZu
        NkMzYUJNU25Kc1hHTWxhYWd4blVxczQKLS0tIHp1d3BxRzJ3Y3FWT3dEK0ZTQlE2
        MWlacTZIVVphbi9hQ0tLQk5oYStGTWMKAILiVz8g1/ctQRb8X179kmQNWLU1kAII
        AaDB4ZzYP29mzHgl14EbQWW+r2uBH4z/E4M2EVnpd1pROAxTtU1ARg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-09T23:43:33Z"
  mac: ENC[AES256_GCM,data:QNYoLKeBA8I9ULeBPpz3qlFK/IBIPrBrFO+WFa+B8Pv2PeutS9M7ZvvqfGUZF/aoHZwsgNsVkMNpsa3DUKk3+q2YbNi5uCvn3c8xBsvvJlunlz3uSMD7ANCiYl4mk/feIYqfYsZoWgvIlbdWYXb5EGUpwos+VfLGgz7yzXqnV5g=,iv:kXIIPagMtRo1BT7J6UOWi1BF6nAAG6ePtTI9pwYnq/U=,tag:4WB2DKXB5HnalBP1qn1Y9g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
